//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMSpriteMaker.resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMMSpriteMaker.resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color_A {
            get {
                return ResourceManager.GetString("Color_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color_B {
            get {
                return ResourceManager.GetString("Color_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color_G {
            get {
                return ResourceManager.GetString("Color_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color_R {
            get {
                return ResourceManager.GetString("Color_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base point: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_BasePoint {
            get {
                return ResourceManager.GetString("ConfigWindow_BasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Caption {
            get {
                return ResourceManager.GetString("ConfigWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Close {
            get {
                return ResourceManager.GetString("ConfigWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipHorizontal {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip image: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipSetting {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipVertical {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_LightSetting {
            get {
                return ResourceManager.GetString("ConfigWindow_LightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Material {
            get {
                return ResourceManager.GetString("ConfigWindow_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emissive: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_MaterialEmissiveColor {
            get {
                return ResourceManager.GetString("ConfigWindow_MaterialEmissiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Face color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_MaterialFaceColor {
            get {
                return ResourceManager.GetString("ConfigWindow_MaterialFaceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specular: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_MaterialSpecularColor {
            get {
                return ResourceManager.GetString("ConfigWindow_MaterialSpecularColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specular power: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_MaterialSpecularPower {
            get {
                return ResourceManager.GetString("ConfigWindow_MaterialSpecularPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel ratio: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_PixelRatio {
            get {
                return ResourceManager.GetString("ConfigWindow_PixelRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rendering back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_RenderingBack {
            get {
                return ResourceManager.GetString("ConfigWindow_RenderingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Render type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_RenderType {
            get {
                return ResourceManager.GetString("ConfigWindow_RenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Reset {
            get {
                return ResourceManager.GetString("ConfigWindow_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewport width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_ViewportWidth {
            get {
                return ResourceManager.GetString("ConfigWindow_ViewportWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z-order range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_ZRange {
            get {
                return ResourceManager.GetString("ConfigWindow_ZRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A texture atlas file is not dropped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ArgsFail {
            get {
                return ResourceManager.GetString("Dialog_ArgsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Caption {
            get {
                return ResourceManager.GetString("Dialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two or more config windows cannot be opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ConfigWindowMultiBootFail {
            get {
                return ResourceManager.GetString("Dialog_ConfigWindowMultiBootFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}/{1}]
        ///Directory: {2}
        ///Input: {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Begin {
            get {
                return ResourceManager.GetString("LogFormat_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled
        ///Succeeded:{0} Failed:{1} Ignored:{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Canceled {
            get {
                return ResourceManager.GetString("LogFormat_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed!!
        ///Succeeded:{0} Failed:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Completed {
            get {
                return ResourceManager.GetString("LogFormat_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0}
        ///Failed... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Fail {
            get {
                return ResourceManager.GetString("LogFormat_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output: {0}, {1}
        ///Succeeded!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Success {
            get {
                return ResourceManager.GetString("LogFormat_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_AutoClose {
            get {
                return ResourceManager.GetString("MakerWindow_AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Caption {
            get {
                return ResourceManager.GetString("MakerWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Close {
            get {
                return ResourceManager.GetString("MakerWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Copy {
            get {
                return ResourceManager.GetString("MakerWindow_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture atlas loader plugins are not found.
        ///Please re-get this tool from an official web site etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextureAtlasLoaderFactory_PluginNotFound {
            get {
                return ResourceManager.GetString("TextureAtlasLoaderFactory_PluginNotFound", resourceCulture);
            }
        }
    }
}
