//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMSpriteMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMMSpriteMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctrl_MainWindow {
            get {
                return ResourceManager.GetString("Ctrl_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config window is not multi-bootable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_MainWindowMultiBootFail {
            get {
                return ResourceManager.GetString("Dialog_MainWindowMultiBootFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xof 0302txt 0064
        ///
        ///template Header {
        /// &lt;3D82AB43-62DA-11cf-AB39-0020AF71E433&gt;
        /// WORD major;
        /// WORD minor;
        /// DWORD flags;
        ///}
        ///
        ///template Vector {
        /// &lt;3D82AB5E-62DA-11cf-AB39-0020AF71E433&gt;
        /// FLOAT x;
        /// FLOAT y;
        /// FLOAT z;
        ///}
        ///
        ///template Coords2d {
        /// &lt;F6F23F44-7686-11cf-8F52-0040333594A3&gt;
        /// FLOAT u;
        /// FLOAT v;
        ///}
        ///
        ///template Matrix4x4 {
        /// &lt;F6F23F45-7686-11cf-8F52-0040333594A3&gt;
        /// array FLOAT matrix[16];
        ///}
        ///
        ///template ColorRGBA {
        /// &lt;35FF44E0-6C7C-11cf-8F52-0040333594A3&gt;
        /// FLOAT red;
        /// FLOAT green;
        /// FLOAT blue; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteAccessory {
            get {
                return ResourceManager.GetString("SpriteAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //======================================
        ///// Sprite effect for MikuMikuMoving
        /////   Generated by MMMSpriteMaker
        /////   Written by ruche
        /////======================================
        ///
        /////--------------------------------------
        ///// Config values
        /////--------------------------------------
        ///
        ///// 0:Sprite
        ///// 1:Sprite (dot by dot)
        ///// 2:Billboard
        ///// 3:Polygon
        ///#define SPRMAKE_CONFIG_DRAWTYPE [[ConfigDrawType]]
        ///
        ///// 0:LeftTop
        ///// 1:MiddleTop
        ///// 2:RightTop
        ///// 3:LeftMiddle
        ///// 4:Center
        ///// 5:RightMiddle
        ///// 6:LeftBot [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteEffect {
            get {
                return ResourceManager.GetString("SpriteEffect", resourceCulture);
            }
        }
    }
}
