//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMSpriteMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMMSpriteMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Base point: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_BasePoint {
            get {
                return ResourceManager.GetString("ConfigWindow_BasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Caption {
            get {
                return ResourceManager.GetString("ConfigWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Close {
            get {
                return ResourceManager.GetString("ConfigWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipHorizontal {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip image: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipSetting {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_FlipVertical {
            get {
                return ResourceManager.GetString("ConfigWindow_FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_LightSetting {
            get {
                return ResourceManager.GetString("ConfigWindow_LightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel ratio: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_PixelRatio {
            get {
                return ResourceManager.GetString("ConfigWindow_PixelRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rendering back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_RenderingBack {
            get {
                return ResourceManager.GetString("ConfigWindow_RenderingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Render type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_RenderType {
            get {
                return ResourceManager.GetString("ConfigWindow_RenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_Reset {
            get {
                return ResourceManager.GetString("ConfigWindow_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewport width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_ViewportWidth {
            get {
                return ResourceManager.GetString("ConfigWindow_ViewportWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z-order range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigWindow_ZRange {
            get {
                return ResourceManager.GetString("ConfigWindow_ZRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A texture atlas file is not dropped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ArgsFail {
            get {
                return ResourceManager.GetString("Dialog_ArgsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Caption {
            get {
                return ResourceManager.GetString("Dialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two or more config windows cannot be opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_ConfigWindowMultiBootFail {
            get {
                return ResourceManager.GetString("Dialog_ConfigWindowMultiBootFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_Center {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_LeftBottom {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_LeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_LeftMiddle {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_LeftMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_LeftTop {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_LeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_MiddleBottom {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_MiddleBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_MiddleTop {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_MiddleTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_RightBottom {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_RightBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_RightMiddle {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_RightMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageBasePoint_RightTop {
            get {
                return ResourceManager.GetString("Enum_ImageBasePoint_RightTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageFlipSetting_Flip {
            get {
                return ResourceManager.GetString("Enum_ImageFlipSetting_Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageFlipSetting_NotFlip {
            get {
                return ResourceManager.GetString("Enum_ImageFlipSetting_NotFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selectable on MMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageFlipSetting_Selectable {
            get {
                return ResourceManager.GetString("Enum_ImageFlipSetting_Selectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Billboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageRenderType_Billboard {
            get {
                return ResourceManager.GetString("Enum_ImageRenderType_Billboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprite (dot by dot) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageRenderType_DotByDotSprite {
            get {
                return ResourceManager.GetString("Enum_ImageRenderType_DotByDotSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageRenderType_Polygon {
            get {
                return ResourceManager.GetString("Enum_ImageRenderType_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_ImageRenderType_Sprite {
            get {
                return ResourceManager.GetString("Enum_ImageRenderType_Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_LightSetting_Disabled {
            get {
                return ResourceManager.GetString("Enum_LightSetting_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_LightSetting_Enabled {
            get {
                return ResourceManager.GetString("Enum_LightSetting_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selectable on MMM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enum_LightSetting_Selectable {
            get {
                return ResourceManager.GetString("Enum_LightSetting_Selectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}/{1}]
        ///Directory: {2}
        ///Input: {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Begin {
            get {
                return ResourceManager.GetString("LogFormat_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled
        ///Succeeded:{0} Failed:{1} Ignored:{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Canceled {
            get {
                return ResourceManager.GetString("LogFormat_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed!!
        ///Succeeded:{0} Failed:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Completed {
            get {
                return ResourceManager.GetString("LogFormat_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0}
        ///Failed... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Fail {
            get {
                return ResourceManager.GetString("LogFormat_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output: {0}, {1}
        ///Succeeded!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogFormat_Success {
            get {
                return ResourceManager.GetString("LogFormat_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_AutoClose {
            get {
                return ResourceManager.GetString("MakerWindow_AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMMSpriteMaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Caption {
            get {
                return ResourceManager.GetString("MakerWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Close {
            get {
                return ResourceManager.GetString("MakerWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakerWindow_Copy {
            get {
                return ResourceManager.GetString("MakerWindow_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xof 0302txt 0064
        ///
        ///template Header {
        /// &lt;3D82AB43-62DA-11cf-AB39-0020AF71E433&gt;
        /// WORD major;
        /// WORD minor;
        /// DWORD flags;
        ///}
        ///
        ///template Vector {
        /// &lt;3D82AB5E-62DA-11cf-AB39-0020AF71E433&gt;
        /// FLOAT x;
        /// FLOAT y;
        /// FLOAT z;
        ///}
        ///
        ///template Coords2d {
        /// &lt;F6F23F44-7686-11cf-8F52-0040333594A3&gt;
        /// FLOAT u;
        /// FLOAT v;
        ///}
        ///
        ///template Matrix4x4 {
        /// &lt;F6F23F45-7686-11cf-8F52-0040333594A3&gt;
        /// array FLOAT matrix[16];
        ///}
        ///
        ///template ColorRGBA {
        /// &lt;35FF44E0-6C7C-11cf-8F52-0040333594A3&gt;
        /// FLOAT red;
        /// FLOAT green;
        /// FLOAT blue; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteAccessory {
            get {
                return ResourceManager.GetString("SpriteAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //======================================
        ///// Sprite effect for MikuMikuMoving
        /////   Generated by MMMSpriteMaker
        /////   Written by ruche
        /////======================================
        ///
        /////--------------------------------------
        ///// Config values
        /////--------------------------------------
        ///
        ///// 0:Sprite
        ///// 1:Sprite (dot by dot)
        ///// 2:Billboard
        ///// 3:Polygon
        ///#define SPRMAKE_CONFIG_RENDERTYPE [[ConfigRenderType]]
        ///
        ///// 0:No
        ///// 1:Yes
        ///#define SPRMAKE_CONFIG_RENDERBACK [[ConfigRenderingBack]]
        ///
        ///// 0:Disabled
        ///// 1:E [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteEffect {
            get {
                return ResourceManager.GetString("SpriteEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The accessory file &apos;{0}&apos; cannot be written. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteMakerFormat_AccessoryFileFail {
            get {
                return ResourceManager.GetString("SpriteMakerFormat_AccessoryFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &apos;{0}&apos; cannot be read as texture atlas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteMakerFormat_BadAtlasFile {
            get {
                return ResourceManager.GetString("SpriteMakerFormat_BadAtlasFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The effect file &apos;{0}&apos; cannot be written. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpriteMakerFormat_EffectFileFail {
            get {
                return ResourceManager.GetString("SpriteMakerFormat_EffectFileFail", resourceCulture);
            }
        }
    }
}
