//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMMSpriteMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ruche.mmm.tools.spriteMaker.EffectFileConfig EffectFileConfig {
            get {
                return ((global::ruche.mmm.tools.spriteMaker.EffectFileConfig)(this["EffectFileConfig"]));
            }
            set {
                this["EffectFileConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ruche.mmm.tools.spriteMaker.AccessoryFileConfig AccessoryFileConfig {
            get {
                return ((global::ruche.mmm.tools.spriteMaker.AccessoryFileConfig)(this["AccessoryFileConfig"]));
            }
            set {
                this["AccessoryFileConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCloseAtSucceeded {
            get {
                return ((bool)(this["AutoCloseAtSucceeded"]));
            }
            set {
                this["AutoCloseAtSucceeded"] = value;
            }
        }
    }
}
